import type { RemoteProduct } from "./schema";

export const MOCK_PRODUCTS: RemoteProduct[] = [
  {
    product_id: "auto-comprehensive",
    product_name: "Comprehensive Car Insurance",
    category: "AUTO",
    short_description: "Full protection for your car, from collisions to theft.",
    long_description:
      "Covers damage to your own vehicle and to third parties, including theft, fire, natural events and glass breakage. Optional roadside assistance available 24/7.",
    monthly_premium_cents: 8900,
    coverage_limit_cents: 5000000,
    deductible_cents: 50000,
    currency: "EUR",
    coverages: [
      { code: "COLLISION", name: "Collision damage", description: "Repairs after an accident, regardless of fault.", included: true },
      { code: "THEFT", name: "Theft & vandalism", description: "Compensation if your car is stolen or vandalised.", included: true },
      { code: "LIABILITY", name: "Third-party liability", description: "Damage you cause to others.", included: true },
      { code: "ROADSIDE", name: "Roadside assistance", description: "Towing and on-site repair.", included: false },
    ],
    terms: { min_age: 18, max_age: 80, term_months: 12 },
    status: "ACTIVE",
  },
  {
    product_id: "home-secure",
    product_name: "Home Secure",
    category: "HOME",
    short_description: "Protect your home and belongings against fire, water and burglary.",
    long_description:
      "Building and contents insurance covering fire, water damage, storms and burglary, plus temporary accommodation if your home becomes uninhabitable.",
    monthly_premium_cents: 4500,
    coverage_limit_cents: 30000000,
    deductible_cents: 25000,
    currency: "EUR",
    coverages: [
      { code: "FIRE", name: "Fire & explosion", description: "Damage to the building and contents.", included: true },
      { code: "WATER", name: "Water damage", description: "Burst pipes and leaks.", included: true },
      { code: "BURGLARY", name: "Burglary", description: "Stolen belongings and forced-entry repairs.", included: true },
      { code: "ACCOMMODATION", name: "Temporary accommodation", description: "Hotel costs while repairs are made.", included: true },
    ],
    terms: { min_age: 21, max_age: 99, term_months: 12 },
    status: "ACTIVE",
  },
  {
    product_id: "health-plus",
    product_name: "Health Plus",
    category: "HEALTH",
    short_description: "Private health cover with fast access to specialists.",
    long_description:
      "Supplementary health insurance with reduced waiting times, specialist consultations, dental and optical care, and a worldwide emergency cover.",
    monthly_premium_cents: 12000,
    coverage_limit_cents: 10000000,
    deductible_cents: 10000,
    currency: "EUR",
    coverages: [
      { code: "SPECIALIST", name: "Specialist consultations", description: "Direct access without referral.", included: true },
      { code: "DENTAL", name: "Dental care", description: "Check-ups, fillings and orthodontics.", included: true },
      { code: "OPTICAL", name: "Optical care", description: "Glasses and lenses allowance.", included: false },
    ],
    terms: { min_age: 0, max_age: 70, term_months: 12 },
    status: "ACTIVE",
  },
  {
    product_id: "life-family",
    product_name: "Family Life Cover",
    category: "LIFE",
    short_description: "Financial security for your loved ones.",
    long_description:
      "Term life insurance paying a lump sum to your beneficiaries. Includes terminal illness benefit and an optional critical illness rider.",
    monthly_premium_cents: 2900,
    coverage_limit_cents: 25000000,
    deductible_cents: 0,
    currency: "EUR",
    coverages: [
      { code: "DEATH", name: "Death benefit", description: "Lump sum to beneficiaries.", included: true },
      { code: "TERMINAL", name: "Terminal illness", description: "Early payout on diagnosis.", included: true },
      { code: "CRITICAL", name: "Critical illness rider", description: "Cancer, stroke and heart attack.", included: false },
    ],
    terms: { min_age: 18, max_age: 65, term_months: 240 },
    status: "ACTIVE",
  },
  {
    product_id: "home-legacy",
    product_name: "Home Classic (legacy)",
    category: "HOME",
    short_description: "Retired product, no longer sold.",
    long_description: "Replaced by Home Secure.",
    monthly_premium_cents: 3000,
    coverage_limit_cents: 15000000,
    deductible_cents: 50000,
    currency: "EUR",
    coverages: [],
    terms: { min_age: 21, max_age: 99, term_months: 12 },
    status: "RETIRED",
  },
];
